GET http://localhost:3080
### funkar som kommentar

GET http://localhost:3080/login
### 

POST http://localhost:3080/login
Content-Type: application/application/json
### 

DELETE http://localhost:3080/login